version: '3'

services:
  app:
    env_file:
      - .env
    build:
      context: ./app
      args:
        HOST_GID: $HOST_GID
        HOST_UID: $HOST_UID
    ports:
      - '8080:80'
    depends_on:
      - db
    links:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    volumes:
      - ./app/public/:/var/www/html/
      - ./app/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    env_file:
      - .env
    image: mysql:5.7
    volumes:
      - ./db/data/:/var/lib/mysql/
